site_name: TransQuest

nav:
    - Home: index.md
    - TransQuest Architectures: architectures.md
    - Pretrained Models: pretrained.md
    - Examples: examples.md
    - Contact: contact.md
theme: material
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/TharinduDR/TransQuest
repo_name: tharindudr/TransQuest
markdown_extensions:
  - admonition
