site_name: TransQuest

nav:
    - Home: index.md
    - TransQuest Architectures: architectures.md
    - Pretrained Models: pretrained.md
    - Examples: examples.md
    - Contact: contact.md
theme: material
markdown_extensions:
  - admonition
